console.log(
    [...new Set(`https://sxyprn.com/
https://www.tubxporn.com/
http://tryanalfisting.com/?nats=MTIzNDc3Ni4xLjExLjIzLjEuMC4wLjAuMA
https://www.playindianporn.net/
https://www.assylum.com/
http://bestanalpornsites.com/
http://www.lesbian8.com/
http://www.viewdesisex.com/
http://www.hotsouthindiansex.com/
http://www.watchindianporn.net/
https://babesrater.com/
http://babedrop.net/
http://xxxpornozone.com/
http://www.xpaja.net/
https://www.avn.com/
https://www.maxim.com/
https://www.playboy.com/products
https://www.menshealth.com/
https://www.cosmopolitan.com/
https://iptorrents.com/torrents/
https://rarbgaccess.org/torrents.php?category=4
http://www.pussytorrents.org/
https://www.freeones.com/
http://www.bestpornstardb.com/
https://www.kindgirls.com/
http://www.largeporntube.com/
http://www.largeporntube.com/popular/47/pantyhose/1.html
http://celebritytube.video/
http://xxxdessert.com/
http://thenewporn.com/
https://www.desihoes.com/
http://www.kporno.com/
https://www.pornjam.com/
https://www.readindiansexstories.com/
https://www.nutaku.net/home/
https://gamcore.com/
https://69games.xxx/
https://adultfriendfinder.com/go/g1424946
https://www.flirt4free.com/rooms/jessica-spencer/
https://www.xlovecam.com/us/?category=1&tdxx=qqj%2FABkFBKQknth6s68jJU6HfRT6gpeO%2Ff329lAvPuDJY7zTlrnw1HZS0JETSI5a%2BeV9VX8fqOPjvCFLVJbR9RQ0Ef%2FMIwtcjqrYOyVA8hUo9TafyiiQc8mlSAZloNXUbF3cOTKxMGDmzH%2B8o1K5tShjG%2FUIPzEhqJyBYbuKWMQXX85LWoMrW4croydgD2DerZEPA%2BrcNbOo9i5G1ljMRg%3D%3D&id_affilie=6419&idpt=5&idspt=6207003538&trac=pornplannercom
https://imlive.com/hostlist.ashx?cat=1&RoomID=10,160&fromsearch=detail&gallery=1&captionid=138
https://www.streamate.com/?AFNO=1-0-641737-356079&DF=0&UHNSMTY=303
https://www.myfreecams.com/
https://www.mydirtyhobby.com/
https://www.webcams.com/webcams
https://sexier.com/
https://www.lovesexxxy.com/?AFNO=1-247331-2-planner
https://www.xpaja.net/
http://www.gfleaks.com/tour/home/?ats=eyJhIjo4NDk5MCwiYyI6NDQ3MjMzMzQsIm4iOjM0LCJzIjo0MTYsImUiOjc3MzIsInAiOjU3fQ==
http://hotteenfeet.com/t/?tracker=pornplannercom&ref=aHR0cDovL3Bvcm5wbGFubmVyLmNvbS8%3D&c=eyJhIjo0NTgsIm8iOjExNywicCI6Mn0g
https://static.babesnetwork.com/landing/tgp9/?ats=eyJhIjo4NDk5MCwiYyI6NDQ3MjMzMzQsIm4iOjE2LCJzIjoxNjYsImUiOjc5MDUsInAiOjU3fQ==
http://www.blazinglink.com/xempire/go.php?pr=12&su=2&si=81&pa=index&ar=&ad=247331&campaign=38453
https://www.iknowthatgirl.com/landing/tour5/?ats=eyJhIjo4NDk5MCwiYyI6NDQ3MjMzMzQsIm4iOjE1LCJzIjoxODEsImUiOjU5MiwicCI6NTd9
https://www.sexyhub.com/?ats=eyJhIjo4NDk5MCwiYyI6NDQ3MjMzMzQsIm4iOjMxLCJzIjoyNzMsImUiOjExMTgsInAiOjU3fQ==
https://www.scoreland.com/home/?nats=MTAwMDQ4MTEuMi4yLjIuNDUuMC4wLjAuMA
https://www.fakehub.com/?ats=eyJhIjo4NDk5MCwiYyI6NDQ3MjMzMzQsIm4iOjMwLCJzIjoyNjEsImUiOjExMDYsInAiOjU3fQ==
http://watchmygf.com/t/?tracker=pornplannercom&ref=aHR0cDovL3Bvcm5wbGFubmVyLmNvbS8%3D&c=eyJhIjo0NTgsIm8iOjI4LCJwIjozfSAg
http://bestpaypornsites.com/
http://paidpornsites.net/
`.split`\n`.filter(v => /^http/.test(v)).map(v => v.replace(/https?:\/\/|www.|(\w+\.)(?=\w+\.\w+)|\/.*/g, '')))]
)
